name: studioflow
version: "1.0.0"
config-version: 2
profile: studioflow

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  studioflow:
    staging:
      +schema: staging
      +materialized: view
