name: studioflow
version: "1.0.0"
config-version: 2
profile: studioflow

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

vars:
  reporting_window_start: "2026-01-01"
  reporting_window_end: "2026-07-01"

seeds:
  studioflow:
    +schema: seed

models:
  studioflow:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: view
