FROM apache/airflow:2.10.4-python3.12

USER airflow

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

ENV DBT_PROFILES_DIR=/opt/airflow/project/dbt
